version: '3.8'

services:
  # Frontend Development Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - api
    restart: unless-stopped

  # Backend API Development Service
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=${MONGODB_URL:-mongodb://mongodb:27017}
      - DATABASE_NAME=${DATABASE_NAME:-nfl_sentiment_dev}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
      - SECRET_KEY=${SECRET_KEY:-dev-secret-key-change-in-production}
      - ALGORITHM=${ALGORITHM:-HS256}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES:-30}
      - DEBUG=true
      - TWITTER_BEARER_TOKEN=${TWITTER_BEARER_TOKEN}
      - ESPN_API_KEY=${ESPN_API_KEY}
      - DRAFTKINGS_API_KEY=${DRAFTKINGS_API_KEY}
      - MGM_API_KEY=${MGM_API_KEY}
      - HUGGINGFACE_TOKEN=${HUGGINGFACE_TOKEN}
      - HOPSWORKS_API_KEY=${HOPSWORKS_API_KEY}
      - WANDB_API_KEY=${WANDB_API_KEY}
    volumes:
      - ./app:/app/app
      - ./logs:/app/logs
    depends_on:
      - mongodb
      - redis
    restart: unless-stopped

  # MongoDB Database
  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD:-password}
      - MONGO_INITDB_DATABASE=${DATABASE_NAME:-nfl_sentiment_dev}
    volumes:
      - mongodb_dev_data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: unless-stopped

  # Redis Cache
  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_dev_data:/data
    restart: unless-stopped

volumes:
  mongodb_dev_data:
  redis_dev_data: