name: CI/CD Pipeline

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    
    services:
      mongodb:
        image: mongo:7.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.adminCommand(\"ping\")'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      
      redis:
        image: redis:7.2-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Cache Python dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt

    - name: Run backend tests
      run: |
        pytest --cov=app --cov-report=xml --cov-report=term-missing
      env:
        TEST_MONGODB_URL: mongodb://localhost:27017
        TEST_REDIS_URL: redis://localhost:6379/1

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: backend
        name: backend-coverage

  test-frontend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Install frontend dependencies
      run: |
        cd frontend
        npm ci

    - name: Run frontend tests
      run: |
        cd frontend
        npm run test:coverage

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./frontend/coverage/lcov.info
        flags: frontend
        name: frontend-coverage

  lint-and-format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt

    - name: Install frontend dependencies
      run: |
        cd frontend
        npm ci

    - name: Run Python linting
      run: |
        black --check app/
        flake8 app/
        mypy app/

    - name: Run frontend linting
      run: |
        cd frontend
        npm run lint

  build:
    runs-on: ubuntu-latest
    needs: [test-backend, test-frontend, lint-and-format]

    steps:
    - uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build -t nfl-sentiment-analyzer .

    - name: Test Docker image
      run: |
        docker run --rm -d --name test-container -p 8000:8000 nfl-sentiment-analyzer
        sleep 10
        curl -f http://localhost:8000/health || exit 1
        docker stop test-container

    # Development branch specific steps
    - name: Development specific checks
      if: github.ref == 'refs/heads/dev'
      run: |
        echo "Running development branch specific checks..."
        # Add development environment specific checks here

    # Main branch specific steps
    - name: Production deployment
      if: github.ref == 'refs/heads/main'
      run: |
        echo "Running production deployment steps..."
        # Add production deployment steps here
